config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get     'help'    => 'static_pages#help'
  get     'about'   => 'static_pages#about'
  get     'contact' => 'static_pages#contact'
  
  get     'signup'  => 'people#new'
  
  
  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'

  resources :people do
    member do
      get :following, :followers
    end
  end
  
  
  resources :posts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class = "posts">
    <%= render @feed_items %>
  </ol>
  
  <%= will_paginate @feed_items %>
  
<% end %>

app/views/shared/_person_info.html.erb
<!--<%= link_to gravatar_for(current_person, size: 50), current_person %>-->



<h1><%= current_person.name %></h1>
<span><%= link_to "view my profile", current_person %></span>
<span><%= pluralize(current_person.posts.count, "post") %></span>

      <h1> 
        <% if current_person.picture? %>
          <%= image_tag( current_person.picture.url, width: '250') %>
        <% else %>
          <%= gravatar_for current_person %>
        <% end %>
        
      </h1>

app/views/shared/_post_form.html.erb
<%= form_for(@post, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new post..." %>
  </div>
  
  <%= f.submit "Post", class: "btn btn-primary" %>
  
  <span class = "picture">
    <%= f.file_field :picture, 
    accept: 'image/jpg, image/jpeg, image/gif, image/png' %>
  </span>
  
<% end %>

<script type = "text/javascript">
  $('#post_picture').bind('change', function()
    {
      size_in_megabytes = this.files[0].size/1024/1024;
      if (size_in_megabytes > 3.5) {
        alert('Maximum file size is 3.5MB  Please resize your image or select a smaller file.');
      }
      
    });
</script>

app/views/shared/_stats.html.erb
<% @person ||= current_person %>
<div class="stats">
  <a href="<%= following_person_path(@person) %>">
    <strong id="following" class="stat">
      <%= @person.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_person_path(@person) %>">
    <strong id="followers" class="stat">
      <%= @person.followers.count %>
    </strong>
    followers
  </a>
</div>