config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get     'help'    => 'static_pages#help'
  get     'about'   => 'static_pages#about'
  get     'contact' => 'static_pages#contact'
  
  get     'signup'  => 'people#new'
  
  
  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'

  resources :people do
    member do
      get :following, :followers
    end
  end
  
  
  resources :posts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  
  <p>
    Discover Hockey App - Rob Anderson, February 2015
  </p> 
  

  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      
      <!--<li><%= link_to "Sign up", signup_path %></li> -->
      
      <li><a href="https://github.com/anderson2" target="_blank">Contact</a></li>

      <!-- 
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "Help", help_path %></li> 
      -->
      
      <li><%= link_to "About", about_path %></li>

    </ul>
  </nav>
  

</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container-fluid">
      
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Discover Hockey", root_path, class: "navbar-brand" %>
  
      </div>
  
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  
        <ul class="nav navbar-nav navbar-right">
          <!-- <li><%= link_to "Sign in", signup_path %></li> -->
          
        <% if logged_in? %>
          <li><%= link_to "People", people_path %></li>
          
          <li><%= link_to "New post", root_path %></li>
          <li><a href="http://stores.ebay.ca/Garrison-Hockey-Cards" target="_blank">Store</a></li>

          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              My Account <b class="caret"></b>
            </a>
            
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "View my profile", current_person %></li>
              <li><%= link_to "Edit/Update Settings", edit_person_path(current_person) %></li>
              <li><%= link_to "About Discover Hockey", about_path %></li>
            </ul>
            

              <li><%= link_to "Sign out", logout_path, method: "delete" %></li>


          </li>
          
        <% else %>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "People", people_path %></li>

          <li><%= link_to "Sign in", login_path %></li>

        <% end %>

        </ul>
        
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>


<!-- Reference doc
http://getbootstrap.com/components/#navbar
-->

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    
    <%= render "layouts/shim" %>
      
  </head>

  <body>
    <%= render "layouts/header" %>

    <div class="container">
      
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      
      <%= yield %>
      
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
     
    </div>
    
  </body>
  
</html>